server: 
    port: 8080

spring: 
    jpa: 
        hibernate: 
            ddl-auto: none
    datasource: 
        url: DB_URL
        username: USER_NAME
        password: PASSWORD
        driverClassName: DRIVER_NAME
        